name: Trigger Release if more than 30 days no releases

on:
  schedule:
    # Every Monday at 04:00
    - cron: '0 4 * * 1'

jobs:
  trigger-check:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Repository Dispatch
        uses: peter-evans/repository-dispatch@26b39ed245ab8f31526069329e112ab2fb224588 # v2.1.1
        with:
          event-type: trigger-release
